Cart
swrw90/react-jwt pull request #20
Opened 2018-05-21 00:50 UTC by swrw90

2018-05-21 01:06 UTC, yhozumi commented on client/src/components/ReviewPurchase/ReviewPurchase.jsx
> +    componentWillMount() {
Do you need this?

2018-05-21 01:06 UTC, yhozumi commented on client/src/components/ReviewPurchase/ReviewPurchase.jsx
> +    closeModal() {
Do you still need this too?

2018-05-21 01:07 UTC, yhozumi commented on client/src/components/ReviewPurchase/ReviewPurchase.jsx
> +// const mapDispatchToProps = dispatch => {
What's this? It's commented out.

2018-05-21 01:08 UTC, yhozumi commented on client/src/redux/reducers/cart.reducer.js
> +    return products.map(calculateIndvidualTotalPrice).reduce(determineFinalTotal);
Beauty

2018-05-21 01:08 UTC, yhozumi commented on client/src/redux/reducers/cart.reducer.js
> +                action.cartItem.quantity++; // move to product
I don't think this should be merged to master until you move these to product reducer.

2018-05-21 01:09 UTC, yhozumi requested changes

2018-05-21 01:09 UTC, yhozumi commented on client/src/redux/reducers/cart.reducer.js
> +                action.cartItem.quantity++; // move to product
Please move this to product reducer before merging to master.

2018-05-21 01:10 UTC, yhozumi commented
🤷🏻‍♂️

2018-05-21 20:27 UTC, yhozumi commented on client/src/redux/reducers/cart.reducer.js
> -            if (action.cartItem.quantity > 0) {
Wait what happened to this check?

2018-05-21 20:29 UTC, yhozumi requested changes

2018-05-21 20:29 UTC, yhozumi commented on client/src/components/Cart/CheckoutForm.jsx
> +    displayTotal(total) {
I don't see any point in this at all.

2018-05-21 20:29 UTC, yhozumi commented on client/src/redux/reducers/product.reducers.js
> +            action.cartItem.quantity++;
This isn't how I want you to do it. You're mutant the state directly. Since it's js/react/redux let's keep it functional.

2018-05-21 20:38 UTC, swrw90 commented on client/src/redux/reducers/cart.reducer.js
> -            if (action.cartItem.quantity > 0) {
It didn't seem necessary, it works without it and to have it meant repeating code.

2018-05-23 03:32 UTC, yhozumi commented on client/src/redux/reducers/cart.reducer.js
> +            if (state.cart.includes(action.cartItem)) {
love this check.

2018-05-23 03:32 UTC, yhozumi commented on client/src/redux/reducers/cart.reducer.js
> +            action.item.quantity++;
🤔

2018-05-23 03:33 UTC, yhozumi approved these changes

2018-05-23 03:33 UTC, merged